//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public comment()
        {
            this.blogreply = new HashSet<blogreply>();
        }
    
        public int id { get; set; }
        public string owner { get; set; }
        public System.DateTime createtime { get; set; }
        public string body { get; set; }
        public int ownlocation { get; set; }
        public bool state { get; set; }
    
        public virtual ICollection<blogreply> blogreply { get; set; }
        public virtual blogs blogs { get; set; }
        public virtual students students { get; set; }
    }
}
