//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class friendfocus
    {
        public bool ifname { get; set; }
        public string name { get; set; }
        public string focus { get; set; }
        public string befocus { get; set; }
        public System.DateTime createtime { get; set; }
        public string nikename { get; set; }
        public string pic { get; set; }
        public bool sex { get; set; }
        public bool ifsex { get; set; }
        public int exp { get; set; }
    }
}
