//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oucfreetalkEntities : DbContext
    {
        public oucfreetalkEntities()
            : base("name=oucfreetalkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<blogreply> blogreply { get; set; }
        public DbSet<blogs> blogs { get; set; }
        public DbSet<comment> comment { get; set; }
        public DbSet<friends> friends { get; set; }
        public DbSet<postc> postc { get; set; }
        public DbSet<postclass> postclass { get; set; }
        public DbSet<postreply> postreply { get; set; }
        public DbSet<posts> posts { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<friendbefocus> friendbefocus { get; set; }
        public DbSet<friendfocus> friendfocus { get; set; }
        public DbSet<accountaccess> accountaccess { get; set; }
        public DbSet<students> students { get; set; }
        public DbSet<groupaccess> groupaccess { get; set; }
        public DbSet<groups> groups { get; set; }
        public DbSet<stumessage> stumessage { get; set; }
        public DbSet<notices> notices { get; set; }
        public DbSet<lostafound> lostafound { get; set; }
        public DbSet<application> application { get; set; }
        public DbSet<burieddata> burieddata { get; set; }
    }
}
