//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class notices
    {
        public int id { get; set; }
        public int noticeclass { get; set; }
        public Nullable<int> postid { get; set; }
        public string stuid { get; set; }
        public Nullable<int> replyid { get; set; }
        public string replystuid { get; set; }
        public bool state { get; set; }
        public Nullable<int> commentsid { get; set; }
        public System.DateTime createtime { get; set; }
    }
}
