//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class postc
    {
        public postc()
        {
            this.postreply = new HashSet<postreply>();
        }
    
        public int id { get; set; }
        public int postlocation { get; set; }
        public string owner { get; set; }
        public System.DateTime createtime { get; set; }
        public string body { get; set; }
        public int ownpost { get; set; }
    
        public virtual posts posts { get; set; }
        public virtual ICollection<postreply> postreply { get; set; }
        public virtual students students { get; set; }
    }
}
