//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class posts
    {
        public posts()
        {
            this.postc = new HashSet<postc>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public System.DateTime createtime { get; set; }
        public System.DateTime updatetime { get; set; }
        public int realbody { get; set; }
        public int body { get; set; }
        public string owner { get; set; }
        public string contenttext { get; set; }
        public int ownclass { get; set; }
        public bool state { get; set; }
    
        public virtual ICollection<postc> postc { get; set; }
        public virtual postclass postclass { get; set; }
        public virtual students students { get; set; }
    }
}
