//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public students()
        {
            this.blogreply = new HashSet<blogreply>();
            this.blogreply1 = new HashSet<blogreply>();
            this.blogs = new HashSet<blogs>();
            this.comment = new HashSet<comment>();
            this.friends = new HashSet<friends>();
            this.friends1 = new HashSet<friends>();
            this.postc = new HashSet<postc>();
            this.postreply = new HashSet<postreply>();
            this.postreply1 = new HashSet<postreply>();
            this.posts = new HashSet<posts>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public bool ifname { get; set; }
        public string nikename { get; set; }
        public string pic { get; set; }
        public string password { get; set; }
        public bool sex { get; set; }
        public bool ifsex { get; set; }
        public System.DateTime birth { get; set; }
        public string year { get; set; }
        public string email { get; set; }
        public bool ifemail { get; set; }
        public string mobile { get; set; }
        public bool ifmobile { get; set; }
        public int exp { get; set; }
        public string family { get; set; }
        public bool ifbirth { get; set; }
        public int accountlevel { get; set; }
    
        public virtual ICollection<blogreply> blogreply { get; set; }
        public virtual ICollection<blogreply> blogreply1 { get; set; }
        public virtual ICollection<blogs> blogs { get; set; }
        public virtual ICollection<comment> comment { get; set; }
        public virtual ICollection<friends> friends { get; set; }
        public virtual ICollection<friends> friends1 { get; set; }
        public virtual ICollection<postc> postc { get; set; }
        public virtual ICollection<postreply> postreply { get; set; }
        public virtual ICollection<postreply> postreply1 { get; set; }
        public virtual ICollection<posts> posts { get; set; }
    }
}
